language: bash

sudo: required

install:
 - sudo apt-get -qq update
 - sudo apt-get install -y udftools coreutils vim-common scrub
 - sudo add-apt-repository -y ppa:gnome3-team/gnome3
 - sudo apt-get -qq update
 - sudo apt-get install -y udisks2
 - curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -
 - echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get -qq update
 - sudo apt-get install -y --allow-unauthenticated shellcheck
 - pip install --user bashate

script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'
 - bash -c 'shopt -s globstar; bashate -i E006 **/*.sh'
 - ./unit-test-linux.sh

matrix:
  fast_finish: true
